adding a return btn to roomName and corner page
GDSC-YU/tuwaiq-classrooms pull request #28
Opened 2022-11-11 18:26 UTC by MaissaAlbaik

The position of the button is annoying any suggestion.

2022-11-12 15:42 UTC, YazeedAlKhalaf requested changes

2022-11-12 15:42 UTC, YazeedAlKhalaf commented on src/pages/classrooms/[roomName].astro
> +    <Icon name="ei:arrow-left" class="w-12 transition-all duration-400 hover:text-white"/>
The button works but put it inside the header. And have the callback, as a prop.

2022-11-12 18:09 UTC, MaissaAlbaik commented on src/pages/classrooms/[roomName].astro
> +    <Icon name="ei:arrow-left" class="w-12 transition-all duration-400 hover:text-white"/>
Will work on that

2022-11-13 06:03 UTC, g9wz requested changes
left some comments, great job!

2022-11-13 06:03 UTC, ghost commented on src/components/Header.tsx
> +import { Children, SVGProps } from "react";
Icon and SVGProps are never used

2022-11-13 06:03 UTC, ghost commented on src/components/Header.tsx
> +    <svg  className="w-11 h-11 hover:text-white ">
Make the icon smaller so it fits the text, or find another one

2022-11-13 06:03 UTC, ghost commented on src/components/Header.tsx
> +      <p className="font-black font-cairo text-4xl"><a href={callback}>{EiArrowLeft()}</a>{title}</p>
The icon and text should be beside each other. You can use flex and space-x for the spacing between them,
 *make sure not to apply it on the whole header since it will affect the SchedulePage too*

2022-11-13 06:03 UTC, ghost commented on src/pages/classrooms/[roomName].astro
> +
sup with the extra lines :D

2022-11-13 06:03 UTC, g9wz commented on src/pages/corners/[corner].astro
> +import { Icon } from "astro-icon";
Icon is not used, unnecessary import

2022-11-13 06:03 UTC, g9wz commented on src/pages/corners/[corner].astro
> +
u really like those extra lines

2022-11-13 08:11 UTC, MaissaAlbaik commented on src/pages/corners/[corner].astro
> +
Yeah, I guess

2022-11-13 08:38 UTC, g9wz approved these changes, later dismissed
LGTM, good job

2022-11-17 10:05 UTC, YazeedAlKhalaf requested changes

2022-11-17 10:05 UTC, YazeedAlKhalaf commented on src/components/Header.tsx
> +      <path fill="currentColor" d="M11.707 5.293a1 1 0 0 1 0 1.414L7.414 11H19a1 1 0 1 1 0 2H7.414l4.293 4.293a1 1 0 0 1-1.414 1.414l-6-6a1 1 0 0 1 0-1.414l6-6a1 1 0 0 1 1.414 0z">
why not use on of the material icons?

2022-11-17 10:05 UTC, YazeedAlKhalaf commented on src/components/Header.tsx
> +      <p className="flex font-black font-cairo text-4xl"><a href={callback}>{MiArrowLeft()}</a>{title}</p>
make the header a flex, better semantics

2022-11-17 10:05 UTC, YazeedAlKhalaf commented on src/components/Header.tsx
> +  callback?:string;
`callback` is not descriptive enough, call it `backButtonHref`

2022-11-17 10:05 UTC, YazeedAlKhalaf commented on src/pages/classrooms/[roomName].astro
> -
put back this space

2022-11-17 10:05 UTC, YazeedAlKhalaf commented on src/pages/corners/[corner].astro
> +    headerColor = HeaderColor.paleBlue;
remove this extra space.

2022-11-17 10:05 UTC, YazeedAlKhalaf commented on src/components/Header.tsx
> -
add this line back

2022-11-17 11:46 UTC, MaissaAlbaik commented on src/components/Header.tsx
> +      <path fill="currentColor" d="M11.707 5.293a1 1 0 0 1 0 1.414L7.414 11H19a1 1 0 1 1 0 2H7.414l4.293 4.293a1 1 0 0 1-1.414 1.414l-6-6a1 1 0 0 1 0-1.414l6-6a1 1 0 0 1 1.414 0z">
I will check them out. Do you have a specific one in mind?

2022-11-17 16:17 UTC, MaissaAlbaik commented on src/components/Header.tsx
> +      <p className="flex font-black font-cairo text-4xl"><a href={callback}>{MiArrowLeft()}</a>{title}</p>
Using the flex in the header will cause the schedule page days to be in the same row as the roomName and backbtn.

2023-01-19 14:24 UTC, closed without merging